export const API_CONFIG = {
  BASE_URL: 'https://api.phhotel.vn',
  TIMEOUT: 30000,
  AI_TIMEOUT: 120000,
  AI_BASE_URL: 'https://ai.phhotel.vn',
};

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/users/login',
    REGISTER: '/users/register',
    FORGOT_PASSWORD: '/users/forgot-password',
    RESET_PASSWORD: '/users/reset-password',
    LOGOUT: '/users/logout',
    REFRESH: '/users/refresh-token',
    PROFILE: '/users/profile',
  },
  ROOMS: {
    BASE: '/rooms',
    BY_ID: (id: string) => `/rooms/${id}`,
    EVENTS: (id: string) => `/rooms/${id}/events`,
    AVAILABLE: '/rooms/available',
    CHECKIN: (id: string) => `/rooms/checkin/${id}`,
    CHECKOUT: (id: string) => `/rooms/checkout/${id}`,
    GUEST_OUT: (id: string) => `/rooms/${id}/guest-out`,
    GUEST_RETURN: (id: string) => `/rooms/${id}/guest-return`,
    BOOKING: '/rooms/booking',
    CANCEL_BOOKING: (id: string) => `/rooms/booking/cancel/${id}`,
    BOOKINGS: '/rooms/bookings',
    HISTORY: '/rooms/history',
  },
  HOTELS: {
    BASE: '/hotels',
    BY_ID: (id: string) => `/hotels/${id}`,
  },
  USERS: {
    BASE: '/users',
    BY_ID: (id: string) => `/users/${id}`,
    BY_HOTEL: (hotelId: string) => `/users/hotel/${hotelId}`,
    ME: '/users/me',
  },
  BOOKINGS: {
    BASE: '/bookings',
    BY_ID: (id: string) => `/bookings/${id}`,
  },
  FINANCIAL: {
    SUMMARY: '/financial-summary',
    EXPORT_EXCEL: '/financial-summary/export-excel',
  },
  REVENUE: {
    BASE: '/revenue',
    BY_ID: (id: string) => `/revenue/${id}`,
    BY_HOTEL: (hotelId: string) => `/revenue/hotel/${hotelId}`,
    DAILY: '/revenue/daily',
    MONTHLY: '/revenue/monthly',
    YEARLY: '/revenue/yearly',
    SUMMARY: '/revenue/summary',
    BY_DATE_RANGE: '/revenue/date-range',
  },
  SERVICES: {
    BASE: '/services',
    BY_ID: (id: string) => `/services/${id}`,
    CATEGORIES: '/services/categories',
    ORDERS: '/services/orders',
    ORDER_BY_ID: (id: string) => `/services/orders/${id}`,
    ORDERS_BY_ROOM: (roomId: string) => `/services/orders/room/${roomId}`,
    ORDERS_BY_HOTEL: '/services/orders/hotel',
    AVAILABLE: '/services/available',
    CHECKOUT: (bookingId: string) => `/services/checkout/${bookingId}`,
    CALCULATE_TOTAL: '/services/calculate-total',
    ASSIGN: '/services/assign',
    BULK_ASSIGN: '/services/bulk-assign',
  },
  STAFFS: {
    BASE: '/staffs',
    BY_ID: (id: string) => `/staffs/${id}`,
    BY_HOTEL: (hotelId: string) => `/staffs/hotel/${hotelId}`,
    CALCULATE_SALARY: (staffId: string) => `/staffs/${staffId}/calculate-salary`,
    PAY_SALARY: (staffId: string) => `/staffs/${staffId}/pay-salary`,
    PAYROLL: '/staffs/payroll',
  },
  GUESTS: {
    BASE: '/guests',
    BY_ID: (id: string) => `/guests/${id}`,
    CREATE_BOOKING: (guestId: string) => `/guests/${guestId}/create-booking`,
    ASSIGN_ROOM: (guestId: string) => `/guests/${guestId}/assign-room`,
    FIND: '/guests/find',
    BY_ROOM: (roomId: string) => `/guests/room/${roomId}`,
    MERGE: '/guests/merge',
  },
  DEBTS: {
    BASE: '/debts',
    BY_ID: (id: string) => `/debts/${id}`,
    SETTLE: (id: string) => `/debts/${id}/settle`,
    LABELS: (id: string) => `/debts/${id}/labels`,
  },
  NOTIFICATIONS: {
    BASE: '/api/settings/announcements',
    BY_ID: (id: string) => `/api/settings/announcements/${id}`,
    UNREAD_COUNT: '/api/settings/announcements/unread-count',
    MARK_AS_READ: (id: string) => `/api/settings/announcements/${id}/read`,
    MARK_ALL_AS_READ: '/api/settings/announcements/read-all',
  },
  TRANSACTIONS: {
    BASE: '/transactions',
    EXPENSE: '/transactions/expense',
    INCOME: '/transactions/income',
  },
  SETTINGS: {
    NOTIFICATION: '/api/settings/notification',
  },
  SHIFT_HANDOVER: {
    BASE: '/shift-handover',
    PREVIOUS_AMOUNT: '/shift-handover/previous-amount',
    REVENUE: '/shift-handover/revenue',
    HISTORY: '/shift-handover/history',
    BY_ID: (id: string) => `/shift-handover/${id}`,
    MANAGER: '/shift-handover/manager',
  },
};
